# Generated by Django 5.1.1 on 2024-10-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='favorite',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='favorite',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='favorite',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
