# Generated by Django 5.1.1 on 2024-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favorite_cooking_time_favorite_health_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
